version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - gocheckcompilerdirectives
    - gocritic
    - goheader
    - gosec
    - misspell
    - nakedret
    - nilerr
    - nosprintfhostport
    - revive
    - sqlclosecheck
    - unconvert
    - unparam
    - whitespace
formatters:
  enable:
    - gofmt
    - goimports
